/**
 * Official Maestro command vocabulary and HTTP-request step generation.
 *
 * The original scaffold emitted an `apiRequest:` / `response:` block, which is not a Maestro
 * command - flows containing it cannot be replayed. Maestro calls APIs from JavaScript
 * (`http.get` / `http.post` / `http.request`) driven by `evalScript` or `runScript`, with
 * results surfaced through `${output.*}`.
 *
 * Sources:
 *   https://docs.maestro.dev/reference/commands-available
 *   https://docs.maestro.dev/maestro-flows/javascript/make-http-requests
 */

/** Every command in the official reference, as of the Maestro docs (48 commands). */
export const MAESTRO_COMMANDS: string[] = [
  'addMedia',
  'assertDarkMode',
  'assertLightMode',
  'assertNoDefectsWithAI',
  'assertNotVisible',
  'assertScreenshot',
  'assertTrue',
  'assertVisible',
  'assertWithAI',
  'back',
  'clearKeychain',
  'clearState',
  'copyTextFrom',
  'doubleTapOn',
  'eraseText',
  'evalScript',
  'extendedWaitUntil',
  'extractTextWithAI',
  'hideKeyboard',
  'inputText',
  'killApp',
  'launchApp',
  'longPressOn',
  'openLink',
  'pasteText',
  'pressKey',
  'repeat',
  'retry',
  'runFlow',
  'runScript',
  'scroll',
  'scrollUntilVisible',
  'setAirplaneMode',
  'setClipboard',
  'setDarkMode',
  'setLocation',
  'setOrientation',
  'setPermissions',
  'startRecording',
  'stopApp',
  'stopRecording',
  'swipe',
  'takeScreenshot',
  'tapOn',
  'toggleAirplaneMode',
  'toggleDarkMode',
  'travel',
  'waitForAnimationToEnd'
];

const COMMAND_SET = new Set(MAESTRO_COMMANDS);

export function isMaestroCommand(key: string): boolean {
  return COMMAND_SET.has(key);
}

export interface ApiRequestSpec {
  method: string;
  url: string;
  headers?: Record<string, string>;
  body?: string;
  /** Status to assert; defaults to 200. */
  expectStatus?: number;
}

export interface ApiStepsResult {
  steps: any[];
  /** Present when the request is too complex to inline safely. */
  script?: { fileName: string; contents: string };
}

/** Verbs with an `http.<verb>` shorthand; anything else goes through `http.request`. */
const SHORTHAND_VERBS = ['get', 'post', 'put', 'delete'];

/**
 * Inline `evalScript` is only safe for a bare request. Headers and bodies would have to be
 * escaped through both YAML and the `${...}` expression, where a stray quote or brace breaks
 * the flow silently - those go to a script file instead.
 */
export function needsScriptFile(spec: ApiRequestSpec): boolean {
  if (spec.headers && Object.keys(spec.headers).length > 0) return true;
  if (spec.body && spec.body.trim().length > 0) return true;
  return !SHORTHAND_VERBS.includes((spec.method || 'GET').toLowerCase());
}

/** Escapes a value for a single-quoted JavaScript string literal. */
function jsSingleQuoted(value: string): string {
  return `'${String(value).replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
}

function buildScriptContents(spec: ApiRequestSpec, outputVar: string): string {
  const verb = (spec.method || 'GET').toLowerCase();
  const url = jsSingleQuoted(spec.url);

  const config: string[] = [];
  if (spec.headers && Object.keys(spec.headers).length > 0) {
    config.push(`  headers: ${JSON.stringify(spec.headers, null, 2).replace(/\n/g, '\n  ')}`);
  }
  if (spec.body && spec.body.trim().length > 0) {
    config.push(`  body: ${JSON.stringify(spec.body)}`);
  }

  let call: string;
  if (SHORTHAND_VERBS.includes(verb)) {
    call = config.length
      ? `http.${verb}(${url}, {\n${config.join(',\n')}\n})`
      : `http.${verb}(${url})`;
  } else {
    const withMethod = [`  method: ${JSON.stringify(spec.method.toUpperCase())}`, ...config];
    call = `http.request(${url}, {\n${withMethod.join(',\n')}\n})`;
  }

  return [
    '// Generated by Flow Recorder.',
    '// https://docs.maestro.dev/maestro-flows/javascript/make-http-requests',
    `const response = ${call};`,
    '',
    `output.${outputVar}Status = response.status;`,
    `output.${outputVar}Body = response.body;`,
    ''
  ].join('\n');
}

export function buildApiSteps(
  spec: ApiRequestSpec,
  opts: { outputVar: string; scriptName?: string }
): ApiStepsResult {
  const status = spec.expectStatus ?? 200;
  const outputVar = opts.outputVar;

  if (!needsScriptFile(spec)) {
    const verb = (spec.method || 'GET').toLowerCase();
    return {
      steps: [
        { evalScript: `\${output.${outputVar} = http.${verb}(${jsSingleQuoted(spec.url)})}` },
        { assertTrue: `\${output.${outputVar}.status == ${status}}` }
      ]
    };
  }

  const scriptName = opts.scriptName || outputVar;
  const fileName = `${scriptName}.js`;
  return {
    steps: [{ runScript: `scripts/${fileName}` }, { assertTrue: `\${output.${outputVar}Status == ${status}}` }],
    script: { fileName, contents: buildScriptContents(spec, outputVar) }
  };
}

/** True for the invalid `apiRequest:` block the old scaffold produced. */
export function isLegacyApiStep(step: any): boolean {
  return Boolean(step && typeof step === 'object' && !Array.isArray(step) && step.apiRequest);
}

/**
 * Rewrites a legacy block into official steps. `durationMs` is dropped - Maestro has no way to
 * assert it, so carrying it forward would only reintroduce an unusable key.
 */
export function legacyApiSpec(step: any): ApiRequestSpec | null {
  if (!isLegacyApiStep(step)) return null;
  const req = step.apiRequest || {};
  return {
    method: req.method || 'GET',
    url: req.url || '',
    headers: req.headers,
    body: req.body,
    expectStatus: step.response?.status ?? 200
  };
}

/** Full conversion, including any script file the request needs. */
export function convertLegacyApiStepFull(step: any, index: number): ApiStepsResult | null {
  const spec = legacyApiSpec(step);
  if (!spec) return null;
  return buildApiSteps(spec, { outputVar: `api${index}`, scriptName: `api-${index}` });
}

export function convertLegacyApiStep(step: any, index: number): any[] | null {
  return convertLegacyApiStepFull(step, index)?.steps ?? null;
}

/**
 * Parses a comma-separated header line, e.g.
 * `Content-Type: application/json, Authorization: Bearer abc`.
 * Splits each entry on the FIRST colon so header values containing colons survive.
 */
export function parseHeaderLine(line: string | undefined): Record<string, string> | undefined {
  if (!line || !line.trim()) return undefined;
  const headers: Record<string, string> = {};
  for (const part of line.split(',')) {
    const idx = part.indexOf(':');
    if (idx <= 0) continue;
    const key = part.slice(0, idx).trim();
    const value = part.slice(idx + 1).trim();
    if (key) headers[key] = value;
  }
  return Object.keys(headers).length ? headers : undefined;
}
